apiVersion: v1
kind: Secret
metadata:
  name: mysql-pass
type: Opaque
data:
  # username: bXlzcWxhZG1pbg==
  password: MVBhc3N3b3JkMDEwNDAy
# u/ mysqladmin p/ 1Password010402 (https://www.base64encode.org/)
